services:
  postgres:
    image: postgres:18.1
    container_name: 'runs-app-db'
    environment:
    - POSTGRES_DB=runs-app
    - POSTGRES_USER=<<YOUR_USERNAME>>
    - POSTGRES_PASSWORD=<<YOUR_PASSWORD>>
    ports:
    - 5442:5432
